//
// Created by kir on 21.05.19.
//

#ifndef CASS_LION_ABSTRACTDATABASECONFIGURATION_H
#define CASS_LION_ABSTRACTDATABASECONFIGURATION_H


class AbstractDatabaseConfiguration {

};


#endif //CASS_LION_ABSTRACTDATABASECONFIGURATION_H
